version: "3.9"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3301:3001"
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /
    depends_on:
      - backend
    ports:
      - "3302:80"
    restart: unless-stopped

