# -*- coding: utf-8 -*-
from pathlib import Path

path = Path(r'frontend/src/pages/PublicStatusPage.jsx')
text = path.read_text()
old_schedule = "            {scheduleLoading ? (\n              <div className=\"flex h-40 items-center justify-center\">\n                <Spinner />\n              </div>\n            ) : (\n              <div className=\"grid gap-4 sm:grid-cols-2 lg:grid-cols-3\">\n                {Object.entries(dayLabels).map(([day, label]) => (\n                  <div key={day} className=\"rounded-2xl border border-white/10 bg-slate-950/70 p-4 shadow-inner shadow-black/20\">\n                    <p className=\"text-xs font-semibold uppercase tracking-wide text-slate-400\">{label}</p>\n                    <p className=\"mt-2 text-lg font-semibold text-white\">\n                      {schedule?.dailyTimes?.[day] ? `${schedule.dailyTimes[day]} WIB` : 'Tidak dijadwalkan'}\n                    </p>\n                  </div>\n                ))}\n              </div>\n            )}\n            {schedule?.paused ? (\n              <Badge variant=\"warning\" className=\"w-fit uppercase tracking-wide\">\n                Penjadwalan otomatis sementara dijeda\n              </Badge>\n            ) : null}"
new_schedule = "            {scheduleLoading ? (\n              <ScheduleGrid values={schedule?.dailyTimes} readOnly loading highlightToday />\n            ) : schedule ? (\n              <ScheduleGrid values={schedule.dailyTimes} readOnly highlightToday />\n            ) : (\n              <DataPlaceholder\n                icon=\"???\"\n                title=\"Jadwal belum tersedia\"\n                description=\"Hubungi administrator untuk mengatur jadwal pengiriman.\"\n              />\n            )}\n            {schedule?.paused ? (\n              <Badge variant=\"warning\" className=\"w-fit uppercase tracking-wide\">\n                Penjadwalan otomatis sementara dijeda\n              </Badge>\n            ) : null}"
if old_schedule not in text:
    raise SystemExit('schedule block not found')
text = text.replace(old_schedule, new_schedule)
old_next = "            {nextRunLoading ? (\n              <div className=\"flex h-32 items-center justify-center\">\n                <Spinner />\n              </div>\n            ) : nextRun?.timestamp ? (\n              <div className=\"space-y-4 rounded-2xl border border-white/10 bg-slate-950/70 p-5\">\n                <div>\n                  <p className=\"text-xs uppercase tracking-wide text-slate-400\">Waktu pengiriman</p>\n                  <p className=\"mt-1 text-2xl font-semibold text-white\">{nextRun.formatted}</p>\n                  <p className=\"text-sm text-slate-400\">{nextRun.timezone}</p>\n                </div>\n                {nextRun.override ? (\n                  <div className=\"rounded-xl border border-amber-400/30 bg-amber-500/15 p-4 text-sm text-amber-100\">\n                    <p className=\"font-semibold\">Override manual aktif</p>\n                    <p>\n                      {nextRun.override.date} pukul {nextRun.override.time}\n                      {nextRun.override.note ? ' - ' + nextRun.override.note : ''}\n                    </p>\n                  </div>\n                ) : (\n                  <Badge variant=\"info\" className=\"w-fit uppercase tracking-wide\">\n                    Mengikuti jadwal default\n                  </Badge>\n                )}\n              </div>\n            ) : (\n              <div className=\"rounded-2xl border border-dashed border-white/10 bg-slate-950/60 p-6 text-sm text-slate-400\">\n                Belum ada jadwal pengiriman berikutnya. Hubungi administrator untuk mengatur jadwal baru.\n              </div>\n            )}"
new_next = "            {nextRunLoading ? (\n              <div className=\"space-y-4 rounded-2xl border border-white/10 bg-slate-950/70 p-5\">\n                <Skeleton className=\"h-3 w-32\" />\n                <Skeleton className=\"h-8 w-44\" />\n                <Skeleton className=\"h-3 w-28\" />\n                <Skeleton className=\"h-16 w-full\" />\n              </div>\n            ) : nextRun?.timestamp ? (\n              <div className=\"space-y-5 rounded-2xl border border-white/10 bg-slate-950/70 p-5\">\n                <div className=\"space-y-1\">\n                  <p className=\"text-xs uppercase tracking-wide text-slate-400\">Waktu pengiriman</p>\n                  <p className=\"mt-1 text-2xl font-semibold text-white\">{nextRun.formatted}</p>\n                  <p className=\"text-sm text-slate-400\">{nextRun.timezone}</p>\n                </div>\n                <div className=\"flex flex-wrap items-center gap-2 text-xs font-semibold uppercase tracking-wide\">\n                  <span className=\"rounded-full bg-primary-500/15 px-3 py-1 text-primary-200\">\n                    {nextRun.override ? 'Override manual' : 'Jadwal default'}\n                  </span>\n                  {schedule?.timezone ? (\n                    <span className=\"rounded-full bg-slate-800/70 px-3 py-1 text-slate-300\">\n                      Zona waktu {schedule.timezone}\n                    </span>\n                  ) : null}\n                </div>\n                {nextRun.override ? (\n                  <div className=\"rounded-xl border border-amber-400/30 bg-amber-500/15 p-4 text-sm text-amber-100\">\n                    <p className=\"font-semibold\">Override aktif</p>\n                    <p>\n                      {nextRun.override.date} pukul {nextRun.override.time}\n                      {nextRun.override.note ? ` \u00b7 ${nextRun.override.note}` : ''}\n                    </p>\n                  </div>\n                ) : (\n                  <p className=\"rounded-xl border border-white/10 bg-slate-950/80 p-4 text-sm text-slate-300\">\n                    Pengiriman akan mengikuti jadwal default harian.\n                  </p>\n                )}\n              </div>\n            ) : (\n              <DataPlaceholder\n                icon=\"??\"\n                title=\"Belum ada jadwal berikutnya\"\n                description=\"Hubungi administrator untuk mengatur jadwal pengiriman yang baru.\"\n              />\n            )}"
if old_next not in text:
    raise SystemExit('next run block not found')
text = text.replace(old_next, new_next)
path.write_text(text)
