name: Keep Alive Ping

on:
  schedule:
    - cron: "*/10 * * * *" # tiap 10 menit sekali
  workflow_dispatch: # supaya bisa dijalankan manual juga

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Keepalive Endpoint
        run: |
          echo "🔔 Pinging keepalive endpoint..."
          curl -fsS --retry 3 https://sigap.databenuanta.id/keepalive
